
ws_proxy:             #ws代理
  - listen: ':8006'   #监听地址
    router: '/ws/a1'  #路由地址
    balance: 'hash'   #使用客户端ip hash选取后端, 没有设置此项，使用随机策略
    server:
      - 192.168.115.11:8006
      - 192.168.115.12:8006
  - listen: ':6200'
    router: '/ws/a2'
    balance: ''
    server:
      - 192.168.115.11:6200
      - 192.168.115.12:6200
